import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { PLAN_CATALOG, PLAN_IDS, normalizePlan, placeholderPriceCents } from "../../shared/domain";
import { Icon } from "../ui";
import "./home.css";
import { trackMarketing } from "../marketing";
const faqs = [
["Can I use a domain I already own?", "Yes. Keep your domain with your current registrar. The setup guide walks you through domain ownership and the email DNS records you need. Your website can stay where it is."],
["What if I already have email somewhere else?", "Prepare your new mailboxes first, then plan your message migration and change mail routing when you’re ready. Keep your previous service active until the transfer and delivery checks are complete."],
["Do I need to understand DNS?", "You’ll get the record names and values to copy, a check for each record, and a specific next step if something needs attention. DNS changes can take time to appear, and your setup progress is saved."],
["Can I use my usual email app?", "The design includes secure IMAP and SMTP connection settings for compatible email apps, alongside webmail. Final client support depends on the mail provider configured for launch."],
["What is the difference between a mailbox and an alias?", "A mailbox has its own sign-in and storage. An alias, like hello@yourcompany.com, delivers messages into an existing mailbox and does not need a separate inbox."],
["Is there a free plan?", "Yes. Sandbox is free: 3 sending domains, 100 emails each UTC day, and 1,000 each month. Launch and Scale raise those limits. Billing is not connected yet."],
["Is Postlane available to buy today?", "This is a preview of the product. The plans shown here are proposed pricing. Live billing, supported mail features, and launch availability are still being finalized."]];
function Brand(){return <span className="hp-brand"><img className="hp-brand-icon" src="/favicon.png" alt="" />postlane<span className="hp-brand-period">.</span></span>}
function CTA({children="Explore email setup",secondary=false}:{children?:React.ReactNode;secondary?:boolean}){return <Link className={`hp-button ${secondary?"hp-secondary":""}`} to="/get-started" onClick={()=>trackMarketing("setup_cta_clicked",{placement:String(children)})}>{children}<Icon name="arrow" /></Link>}
export function HomePage(){
useEffect(()=>{document.title="Postlane — Business email, simplified";trackMarketing("homepage_viewed");},[]);
const [menu,setMenu]=useState(false);const [tab,setTab]=useState("Inbox");const [seats,setSeats]=useState(1);const [plan,setPlan]=useState("Sandbox");
const selectedPlan=PLAN_CATALOG[normalizePlan(plan.toLowerCase())];
const estimate=placeholderPriceCents(selectedPlan.id,seats)/100;
const messages=tab==="Inbox"?[["MC","Morgan Chen","09:41","A little idea. A big next step.","Let’s make something great together."],["JL","Jamie Lee","09:12","The proposal looks great","Thanks, Alex. We’re ready when you are."],["P","Postlane","08:30","Welcome to your new inbox","Your business has a new home for email."]]:tab==="Sent"?[["AL","To Morgan Chen","09:45","Re: A little idea. A big next step.","I’m in. Let’s get started this week."],["AL","To Jamie Lee","Yesterday","Your proposal is ready","Here’s the plan we talked about."]]:[["AL","To the team","Saved","A fresh start","Hello team, welcome to our new workspace."]];
return <div className="hp"><a className="hp-skip" href="#home-content">Skip to content</a><div className="hp-announcement"><span>PRODUCT PREVIEW</span> Business email, now in product preview. <a href="#how-it-works">Take a look ↗</a></div><header className="hp-header"><div className="hp-container hp-nav-wrap"><Link to="/" aria-label="Postlane home"><Brand /></Link><button className="hp-menu-button" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} aria-controls="homepage-nav" onClick={()=>setMenu(!menu)}><Icon name="menu" /></button><nav id="homepage-nav" className={menu?"hp-nav is-open":"hp-nav"} aria-label="Main navigation">{[["features","Why Postlane"],["how-it-works","How it works"],["pricing","Pricing"],["faq","FAQs"]].map(([id,t])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{t}</a>)}<Link to="/login" className="hp-login">Log in</Link><CTA /></nav></div></header>
<main id="home-content"><section className="hp-container hp-hero"><div className="hp-hero-copy"><div className="hp-kicker"><span /> BUSINESS EMAIL, SIMPLIFIED</div><h1>Your business.<br/>Your name.<br/><em>Your email.</em></h1><p>Professional email on your domain. Guided setup, straightforward pricing, and one place to manage your team.</p><div className="hp-hero-actions"><CTA>Explore email setup</CTA><a className="hp-text-link" href="#pricing">See plans ↗</a></div><p className="hp-launch-note">Explore the setup preview. Live availability and plan terms are still being finalized.</p><div className="hp-hero-notes"><span><Icon name="check"/> Bring your domain</span><span><Icon name="check"/> Keep your website</span></div></div><div className="hp-product-stage"><div className="hp-stage-caption"><span>YOUR NEXT CHAPTER STARTS WITH HELLO</span><Icon name="arrow"/></div><div className="hp-email-address"><span className="hp-address-icon"><Icon name="mail"/></span><span>hello<span className="hp-address-at">@</span>northstar.studio</span><span className="hp-address-check"><Icon name="check"/></span></div><div className="hp-inbox"><div className="hp-inbox-top"><span className="hp-mini-logo"><Icon name="mail"/> Northstar Studio</span><span className="hp-user">AL</span></div><div className="hp-inbox-layout"><div className="hp-inbox-nav"><span className="hp-compose"><Icon name="plus"/> New message</span>{["Inbox","Sent","Drafts"].map(t=><button key={t} className={tab===t?"selected":""} aria-pressed={tab===t} onClick={()=>setTab(t)}><Icon name={t==="Inbox"?"mail":t==="Sent"?"arrow":"grid"}/>{t}{t==="Inbox"&&<b>3</b>}</button>)}<span className="hp-inbox-bottom"><Icon name="shield"/> Your workspace</span></div><div className="hp-messages"><div className="hp-message-heading"><h2>{tab}</h2><span>Product preview</span></div>{messages.map(([initials,name,time,subject,snippet],i)=><div key={subject} className={`hp-message ${i===0?"hp-message-first":""}`}><span className={`hp-person hp-person-${i}`}>{initials}</span><div><div className="hp-message-meta"><strong>{name}</strong><time>{time}</time></div><h3>{subject}</h3><p>{snippet}</p></div></div>)}<div className="hp-inbox-foot"><span>One address. A world of possibility.</span><Icon name="globe"/></div></div></div></div><div className="hp-ready"><span className="hp-ready-icon"><Icon name="check"/></span><div><strong>A good first impression, delivered.</strong><span>Your name belongs after the @.</span></div></div></div></section>
<div className="hp-container hp-use-cases"><span>FOR THE WORK YOU’RE BUILDING</span><div><Icon name="users"/> Small teams</div><div><Icon name="grid"/> Independent businesses</div><div><Icon name="globe"/> Studios & agencies</div></div>
<section id="features" className="hp-section hp-container"><div className="hp-section-heading"><div><div className="hp-kicker">ROOM FOR YOUR NEXT BIG THING</div><h2>A proper home<br/>for business email.</h2></div><p>Everything has its place. Your domain, your people, and the conversations that move your business forward.</p></div><div className="hp-feature-grid"><article className="hp-feature hp-feature-main"><div className="hp-feature-icon"><Icon name="globe"/></div><h3>A name that’s unmistakably yours.</h3><p>Send from your own domain. Give your team individual mailboxes and shared addresses a clear destination.</p><div className="hp-address-list">{[["A","alex","Mailbox"],["H","hello","Alias"],["T","team","Alias"]].map(([i,n,t],k)=><div key={n}><span className={`hp-person hp-person-${k}`}>{i}</span><strong>{n}@northstar.studio</strong><span>{t}</span></div>)}</div></article><article className="hp-feature"><div className="hp-feature-icon"><Icon name="check"/></div><h3>One clear next step.</h3><p>Know what’s ready and what needs attention. Guided domain setup keeps the technical details manageable.</p><div className="hp-mini-checks"><span><Icon name="check"/> Domain ownership verified</span><span><Icon name="check"/> Mailboxes prepared</span><span className="hp-check-next"><span>3</span> Connect your email <Icon name="arrow"/></span></div></article><article className="hp-feature"><div className="hp-feature-icon"><Icon name="settings"/></div><h3>Your team, in one place.</h3><p>Add mailboxes, manage aliases, and see your storage. A focused control panel keeps everyday admin simple.</p><div className="hp-storage"><div><span>Workspace storage</span><strong>4.2 <span>/ 20 GB</span></strong></div><div className="hp-storage-track"><span/></div><small>Room to keep the conversation going.</small></div></article></div></section>
<section className="hp-container hp-trust"><div><div className="hp-kicker">CONFIDENCE STARTS WITH CLARITY</div><h2>Know what you’re getting.</h2><p>A mailbox has its own sign-in and storage. An alias gives that mailbox another address. Your proposed plan makes that distinction clear.</p></div><div className="hp-trust-items"><article><Icon name="shield"/><h3>Understand the security approach</h3><p>Read the controls planned for account access, domain ownership, and recovery.</p><Link to="/security">Read the security approach ↗</Link></article><article><Icon name="card"/><h3>See the cost before you commit</h3><p>Compare proposed storage and mailbox prices. Final taxes, renewal, and cancellation terms must be shown before purchase.</p><a href="#pricing">Calculate your estimate ↗</a></article><article><Icon name="help"/><h3>Find a useful next step</h3><p>Start with practical setup guidance. Published support hours and contact details will follow before launch.</p><Link to="/help">Browse the help center ↗</Link></article></div></section>
<section id="how-it-works" className="hp-how"><div className="hp-container"><div className="hp-section-heading"><div><div className="hp-kicker">FROM DOMAIN TO FIRST SEND</div><h2>A fresh start.<br/>A straightforward setup.</h2></div><p>No guessing where to go next. Follow the guide, check your connection, and get on with your day.</p></div><div className="hp-steps">{[["01","Bring your domain","Use the domain you already own. Verify it with a simple record at your DNS provider.","globe"],["02","Make space for your team","Create your mailboxes and aliases before switching where your email is delivered.","users"],["03","Connect. Check. Send.","Add your email records, verify delivery, and open your new inbox.","mail"]].map(([n,t,d,i])=><article key={n}><div className="hp-step-top"><span>{n}</span><Icon name={i}/></div><h3>{t}</h3><p>{d}</p></article>)}</div><div className="hp-how-bottom"><span><Icon name="clock"/> DNS taking a little longer? Save your progress and come back.</span><CTA secondary>Explore email setup</CTA></div></div></section>
<section className="hp-container hp-migration"><div className="hp-migration-symbol"><Icon name="migration"/></div><div><div className="hp-kicker">A NEW HOME. A FAMILIAR ADDRESS.</div><h2>Already have business email?</h2><p>Bring your address with you. Prepare your new mailboxes, plan the move, and switch delivery when everything is ready.</p><Link className="hp-button hp-secondary" to="/migration" onClick={()=>trackMarketing("migration_guide_clicked",{placement:"homepage"})}>Move your existing email <Icon name="arrow"/></Link></div></section>
<section id="pricing" className="hp-pricing"><div className="hp-container"><div className="hp-pricing-heading"><div className="hp-kicker">START SMALL. MAKE ROOM AS YOU GROW.</div><h2>A little space for every big idea.</h2><p>Choose the mailbox that fits your team.</p><span className="hp-preview-label">Proposed pricing · Product preview</span></div><div className="hp-plans">{PLAN_IDS.map((id)=>{const spec=PLAN_CATALOG[id];return <article className={`hp-plan ${id==="launch"?"hp-plan-business":""}`} key={id}><div className="hp-plan-top"><h3>{spec.label}</h3><span>{spec.tagline}</span></div><div className="hp-plan-price">${spec.priceCents/100}<div>per workspace / month<br/><span>{spec.billed}</span></div></div><p>{spec.blurb}</p><ul>{spec.features.map(x=><li key={x}><Icon name="check"/>{x}</li>)}</ul><CTA secondary={id!=="launch"}>Preview {spec.label} setup</CTA></article>;})}</div><div className="hp-calculator"><div><strong>A clear view of your monthly total.</strong><span>Estimate using the proposed plans.</span></div><label>Plan<select value={plan} onChange={e=>{const next=e.target.value;const nextSpec=PLAN_CATALOG[normalizePlan(next.toLowerCase())];setPlan(next);setSeats((n)=>Math.min(n,nextSpec.maxMailboxes));trackMarketing("pricing_estimate_changed",{plan:next,mailboxes:Math.min(seats,nextSpec.maxMailboxes)});}}>{PLAN_IDS.map(id=><option key={id}>{PLAN_CATALOG[id].label}</option>)}</select></label><label>Mailboxes<input type="number" min="1" max={selectedPlan.maxMailboxes} value={seats} onChange={e=>setSeats(Math.max(1,Math.min(selectedPlan.maxMailboxes,Number(e.target.value)||1)))}/></label><output aria-live="polite">${estimate}<span> / month</span></output></div><p className="hp-price-note">Illustrative USD pricing before tax. Free is limited to one mailbox. Final features, billing terms, and availability will be confirmed before purchase.</p></div></section>
<section id="faq" className="hp-container hp-faq"><div><div className="hp-kicker">A FEW THINGS YOU MIGHT WONDER</div><h2>Good questions.<br/>Clear answers.</h2><p>Your next step should feel simple.</p><Link className="hp-text-link" to="/help">Visit help ↗</Link></div><div className="hp-faq-list">{faqs.map(([q,a])=><details key={q} onToggle={e=>{if(e.currentTarget.open)trackMarketing("faq_opened",{question:q});}}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
<section className="hp-container hp-final"><div className="hp-kicker">YOUR NAME. YOUR NEXT CHAPTER.</div><h2>Good things start<br/>with a <em>hello.</em></h2><p>Give your business an email address to call its own.</p><CTA>Explore email setup</CTA><span className="hp-final-note">Product preview · No live mailbox is activated by this page.</span></section></main><footer className="hp-container hp-footer hp-footer-expanded"><div><Link to="/" aria-label="Postlane home"><Brand/></Link><p>Business email, with room to grow.</p><span className="hp-preview-label">Currently in product preview</span></div><div className="hp-footer-groups">{[["Product",[["/get-started","Explore setup"],["/#pricing","Proposed plans"],["/migration","Move your email"]]],["Company",[["/about","About Postlane"],["/contact","Contact"],["/security","Security approach"]]],["Resources",[["/help","Help center"],["/status","Service status"],["/abuse","Report abuse"]]],["Policies",[["/privacy","Privacy information"],["/terms","Service terms"],["/acceptable-use","Acceptable use"]]]].map(([group,links])=><nav key={String(group)} aria-label={String(group)}><strong>{String(group)}</strong>{(links as string[][]).map(([href,label])=>href.includes('#')?<a key={href} href={href}>{label}</a>:<Link key={href} to={href}>{label}</Link>)}</nav>)}</div><div className="hp-footer-bottom"><span>© {new Date().getFullYear()} Postlane</span><span>Preview pricing and features · Company and final policies to be published before launch</span></div></footer></div>
}
