import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Icon } from '../ui';
import { trackMarketing } from '../marketing';
import './home.css';

type Section = { title: string; body: string };
const content: Record<string, {title: string; intro: string; sections: Section[]}> = {
  'get-started': {title:'Your next step starts here.',intro:'Explore the Postlane signup and setup experience. This is a product preview; creating an account does not guarantee a live mailbox or start a paid plan.',sections:[{title:'1. Create your account',body:'Use an existing email address you can access. Keep recovery separate from the domain you plan to host.'},{title:'2. Prepare your workspace',body:'Explore your domain, mailbox, and team settings. Review provider availability before changing any live DNS records.'},{title:'3. Activate when everything is ready',body:'Live activation depends on confirmed plan terms, provider provisioning, domain ownership, and successful sending and receiving checks.'}]},
  about:{title:'A clearer start for business email.',intro:'Postlane is being designed for small teams, independent businesses, and studios that want email on their own domain without a confusing setup.',sections:[{title:'Our focus',body:'Clear next steps, understandable mailbox pricing, and a single place to manage domains and people.'},{title:'Where we are today',body:'The product is in preview. Plans, supported mail features, and launch availability are still being finalized.'},{title:'Who operates the service',body:'The operating company and business contact details have not yet been published. They must be provided before commercial launch.'}]},
  migration:{title:'Move your email with a plan.',intro:'Keep your business address and prepare the move before changing incoming mail delivery.',sections:[{title:'Prepare every recipient',body:'List your current mailboxes, aliases, forwarding rules, and shared addresses. Create matching destinations before switching MX records.'},{title:'Copy and check your messages',body:'Keep the old service active. Use a supported migration method, inspect skipped items, and compare source and destination before the final sync.'},{title:'Switch delivery when ready',body:'Change MX records only after your destination is ready. Check sender authentication, run a final sync, and verify both sending and receiving before closing the previous service.'},{title:'Confirm what can move',body:'Migration capability depends on the source and destination provider. Contacts, calendars, labels, and rules may need separate handling; no automated migration availability is promised during preview.'}]},
  security:{title:'Understand the protections before you move.',intro:'These are the security requirements guiding the product. They are not a certification or a claim that every control has been independently verified.',sections:[{title:'Account and workspace access',body:'Workspace permissions should be separate from permission to read a mailbox. Sensitive account changes should require recent authentication.'},{title:'Domain and sender checks',body:'Ownership verification, routing checks, and sender authentication are part of setup. Authentication does not guarantee that a message lands in the inbox.'},{title:'Credentials and recovery',body:'Use a reachable recovery address outside your hosted domain. Never send passwords or recovery codes in a support request.'},{title:'Before commercial launch',body:'The operator must confirm the mail provider, hosting regions, encryption details, backup and recovery policy, retention periods, and incident reporting channel.'}]},
  help:{title:'A little guidance at the right moment.',intro:'Start with the issue you’re trying to solve.',sections:[{title:'DNS records are not detected',body:'Check that you edited the authoritative DNS provider. Compare record type, name, and value. Some providers append the domain automatically; cached results can take time to update.'},{title:'A mailbox cannot send',body:'Check mailbox status, storage, mail client authentication, and the provider’s SMTP settings. Verify the sender records before retrying.'},{title:'Mailbox or alias?',body:'A mailbox has its own sign-in and storage. An alias routes another address into an existing mailbox. Plan recipient addresses before changing mail delivery.'},{title:'Need individual help?',body:'Signed-in users can access workspace support from the application. Public support hours and a verified business contact will be published before launch.'}]},
  contact:{title:'Contact and support.',intro:'Choose the right place for your question. Public business contact details are not configured yet.',sections:[{title:'Workspace support',body:'Use the support page in your signed-in workspace to include the relevant domain and problem. Do not include credentials or private message content.'},{title:'Business enquiries',body:'A verified company contact and support schedule will be published here before launch. No response-time commitment is currently offered.'}]},
  status:{title:'Service status is not yet published.',intro:'Live monitoring is not connected to this preview. This page does not indicate that mail delivery is healthy or available.',sections:[{title:'What the live page will report',body:'Mail delivery, webmail, provisioning, DNS checking, and account access will be reported separately, with timestamps and affected regions.'},{title:'During an incident',body:'Published updates should describe customer impact, available workarounds, the next update, and resolution. A live status provider must be connected before launch.'}]},
  privacy:{title:'Privacy information before launch.',intro:'A final privacy notice has not been published. Do not submit private mailbox content through this design preview.',sections:[{title:'What must be disclosed',body:'The operating company must explain the data collected for accounts, billing, support, and mail service; why it is used; the providers involved; and applicable retention periods.'},{title:'Your choices and requests',body:'The published notice must include a verified contact for access, deletion, and other privacy requests, along with relevant regional details.'},{title:'Homepage measurement',body:'The added homepage analytics hooks dispatch local browser events only. They do not send data to an analytics vendor or store identifiers. A production integration needs its own reviewed data and consent policy.'}]},
  terms:{title:'Service terms are being prepared.',intro:'No final service agreement or commercial offer is presented on this preview page.',sections:[{title:'Before a purchase',body:'The operator must publish the contracting entity, supported service, exact price and tax treatment, billing interval, renewal, cancellation, and refund terms.'},{title:'Your mail and account',body:'The final agreement must explain suspension, storage limits, export, deletion, retention, and the responsibilities of the customer and provider.'},{title:'Preview prices',body:'All prices on this site are illustrative. The setup preview does not establish a service guarantee or paid entitlement.'}]},
  'acceptable-use':{title:'Responsible email starts with clear rules.',intro:'The following are proposed product principles. Final acceptable-use terms must be published before live service activation.',sections:[{title:'Respect recipients',body:'The service is intended for legitimate business correspondence. Unsolicited bulk mail, phishing, malware, and impersonation are incompatible with that purpose.'},{title:'Protect the service',body:'Accounts must not be used to evade sending limits or compromise others. The operator must document enforcement, notifications, and an appeal path.'},{title:'Report suspected abuse',body:'A monitored abuse contact must be established before launch. The reporting page explains what information to prepare without exposing private credentials.'}]},
  abuse:{title:'Report suspected misuse.',intro:'A public abuse-reporting channel is not configured yet. Nothing submitted through this preview is sent to an abuse team.',sections:[{title:'Prepare useful evidence',body:'Record the sender address, approximate timestamp with time zone, and relevant message headers. Explain the suspected misuse briefly.'},{title:'Keep private information private',body:'Never include passwords, access tokens, recovery codes, or unrelated private message content.'},{title:'Before launch',body:'The operator must publish a monitored reporting address or secure report form, confirmation workflow, and handling policy.'}]},
};
export function MarketingPage({page}:{page?:string}){const params=useParams();const key=page??params.page??'about';const item=content[key]??content.about;useEffect(()=>{const previous=document.title;document.title=`${item.title.replace(/\.$/,'')} — Postlane`;return()=>{document.title=previous};},[item.title]);return <div className="hp"><header className="hp-header"><div className="hp-container hp-nav-wrap"><Link className="hp-brand" to="/"><span className="hp-brand-icon"><Icon name="mail"/></span>postlane.</Link><Link className="hp-text-link" to="/">← Back to homepage</Link></div></header><main className="hp-container hp-info"><div className="hp-kicker">POSTLANE / PRODUCT PREVIEW</div><h1>{item.title}</h1><p className="hp-info-intro">{item.intro}</p>{item.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.body}</p></section>)}<div className="hp-info-actions">{key==='get-started'?<Link className="hp-button" to="/signup" onClick={()=>trackMarketing('preview_signup_clicked',{placement:'introduction'})}>Continue to signup preview <Icon name="arrow"/></Link>:key==='migration'?<Link className="hp-button" to="/get-started">Explore email setup <Icon name="arrow"/></Link>:<Link className="hp-button hp-secondary" to="/help">Browse help</Link>}{['contact','help'].includes(key)&&<Link className="hp-text-link" to="/support">Workspace support ↗</Link>}<Link className="hp-text-link" to="/">Back to Postlane</Link></div></main></div>}
